import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { communData } from "../data/commun";
import { Layout } from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>{communData.siteName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fmbmecanics.png" />
      </Head>
      <Layout>
        <div className={styles.container}>
          <main className={styles.main}>
            <div className={styles.titleContainer}>
              <h1 className={styles.title}>{communData.siteName}</h1>
            </div>
          </main>
        </div>
      </Layout>
    </>
  );
}
