import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { communData } from "../data/commun";
import { homeData } from "../data/home";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{communData.siteName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fmbmecanics.png" />
      </Head>

      <main className={styles.main}>
        <Image src="/fmbmecanics.png" width={200} height={200} />
        <h1 className={styles.title}>{communData.siteName}</h1>
      </main>

      <footer className={styles.footer}>{communData.siteName}</footer>
    </div>
  );
}
