import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { communData } from "../data/commun";
import { Layout } from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>{communData.siteName}</title>
        <meta
          key="description"
          name="description"
          content="Generated by create next app"
        />
        <meta key="no-folow" name="robots" content="noindex, follow" />
        <link rel="icon" href="/fmbmecanics.png" />
      </Head>
      <Layout noPadding={true}>
        <div className={styles.container}>
          <main className={styles.main}>
            <div className={styles.titleContainer}>
              <h1 className={styles.title}>{communData.siteName}</h1>
              <h2 className={styles.subtitle}>Joël Guibert</h2>
            </div>
          </main>
        </div>
      </Layout>
    </>
  );
}
